# Default server configuration.
host: 127.0.0.1
port: 3000
postgres:
  host: localhost
  port: 5432
  database_name: appdb
  username: postgres
  password: postgres
  useSSL: false
  time_zone: UTC
jwt_secret: "a4Rl5yqAkIQotDIIVG8a8xKWnJ6HHved"